# Generated by Django 5.0.2 on 2024-02-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0002_rename_is_student_student_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
