# Generated by Django 5.0.2 on 2024-03-28 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('student_registration', '0005_student_groups_student_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='register',
            unique_together={('student', 'course')},
        ),
    ]
