# Generated by Django 5.0.2 on 2024-02-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('img', models.ImageField(null=True, upload_to='')),
                ('subject', models.CharField(max_length=50)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Difficult', 'Difficult')], default='Easy', max_length=10)),
                ('descrption', models.TextField(max_length=500)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
