# Generated by Django 5.0.2 on 2025-03-03 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseMultipleOption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('url_video', models.URLField(blank=True)),
                ('phrase_multiple_option', models.TextField(blank=True)),
                ('answer_correct_multiOption', models.CharField(blank=True, max_length=50)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Exercise_passed',
            fields=[
                ('key', models.AutoField(primary_key=True, serialize=False)),
                ('CustomUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercise', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercisemultipleoption')),
            ],
            options={
                'unique_together': {('CustomUser', 'exercise')},
            },
        ),
        migrations.CreateModel(
            name='Exercise_options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_option', models.CharField(max_length=100)),
                ('exerciseMultipleOption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exercises.exercisemultipleoption')),
            ],
            options={
                'unique_together': {('exerciseMultipleOption', 'answer_option')},
            },
        ),
    ]
