# Generated by Django 5.0.2 on 2024-03-13 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_passed_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_passed',
            name='multiple_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.multipleoption'),
        ),
        migrations.AlterField(
            model_name='exercise_passed',
            name='to_complete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.tocomplete'),
        ),
    ]
