# Generated by Django 5.0.2 on 2024-03-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_alter_exercise_passed_multiple_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise_passed',
            name='message',
        ),
    ]
