# Generated by Django 5.0.2 on 2024-03-28 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0005_alter_multipleoption_id_alter_tocomplete_id_and_more'),
        ('lessons', '0002_alter_lesson_id_alter_lesson_numberofecercises'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multipleoption',
            name='description',
        ),
        migrations.RemoveField(
            model_name='multipleoption',
            name='id',
        ),
        migrations.RemoveField(
            model_name='multipleoption',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='multipleoption',
            name='url_video',
        ),
        migrations.RemoveField(
            model_name='tocomplete',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tocomplete',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tocomplete',
            name='lessons',
        ),
        migrations.RemoveField(
            model_name='tocomplete',
            name='url_video',
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('url_video', models.URLField(blank=True)),
                ('lessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='exercise_passed',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='exercise_passed',
            name='exercise',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='multipleoption',
            name='exercise',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='tocomplete',
            name='exercise',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='exercises.exercise'),
        ),
        migrations.AlterUniqueTogether(
            name='exercise_passed',
            unique_together={('student', 'exercise')},
        ),
        migrations.RemoveField(
            model_name='exercise_passed',
            name='multiple_option',
        ),
        migrations.RemoveField(
            model_name='exercise_passed',
            name='to_complete',
        ),
    ]
