# Generated by Django 5.0.2 on 2024-03-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_remove_multipleoption_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tocomplete',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='answer_correct_multiOption',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='exercise',
            name='answers_multiple_option',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='phrase_complete',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='phrase_multiple_option',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type_exercise',
            field=models.CharField(choices=[('Multiple Option', 'Multiple Option'), ('Complete', 'Complete')], default='Complete', max_length=100),
        ),
        migrations.AddField(
            model_name='exercise',
            name='words_complete',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='MultipleOption',
        ),
        migrations.DeleteModel(
            name='ToComplete',
        ),
    ]
