# Generated by Django 5.0.2 on 2024-05-30 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_exercisemultipleoption_exercise_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisemultipleoption',
            name='answers_multiple_option',
        ),
    ]
