# Generated by Django 5.0.2 on 2024-05-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_remove_exercisemultipleoption_answers_multiple_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise_options',
            name='exerciseMultipleOption',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='options', serialize=False, to='exercises.exercisemultipleoption'),
        ),
    ]
