# Generated by Django 5.0.2 on 2024-05-30 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_alter_exercise_options_exercisemultipleoption'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercise_options',
        ),
    ]
