# Generated by Django 5.0.2 on 2024-05-30 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0014_exercise_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise_options',
            unique_together={('exerciseMultipleOption', 'answer_option')},
        ),
    ]
