# Generated by Django 5.0.2 on 2024-03-28 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='numberOfEcercises',
            field=models.IntegerField(verbose_name='Number of Exercises'),
        ),
    ]
